jobs:
  git-release:
    needs: release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Github Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: v${{ needs.release.outputs.stripped_version }}
        files: '"web3j-"+${{ steps.release_name.outputs.result }}.*

          '
        prerelease: false
        repo_token: ${{ secrets.GITHUB_TOKEN }}
  javadocs-release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Javadoc release
      run: ./gradlew -Dorg.ajoberstar.grgit.auth.username=${{ secrets.GITHUB_TOKEN
        }} core:gitPublishPush
  release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OSSRH_GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
      OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_WEB3J_USERNAME }}
    outputs:
      stripped_version: ${{ steps.release_name.outputs.result }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Build Workflow Dispatch
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        owner: hyperledger
        propagate_failure: true
        repo: web3j
        trigger_workflow: true
        wait_interval: 10
        wait_workflow: true
        workflow_file_name: build.yml
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - continue-on-error: true
      name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: ${{ runner.os }}-gradle
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      id: release_name
      name: Release name
      uses: actions/github-script@v4
      with:
        result-encoding: string
        script: 'const branch_name = process.env.GITHUB_REF

          const web3j_release_version = branch_name.substring(branch_name.lastIndexOf(''/'')
          +1 ,branch_name.length  )

          process.env.VERSION = web3j_release_version

          return web3j_release_version

          '
    - continue-on-error: true
      name: Build and stage release
      run: ./gradlew publish -Pversion=${{ steps.release_name.outputs.result }}
    - continue-on-error: true
      name: Release
      run: ./gradlew closeAndReleaseRepository
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
